# 支付宝沙箱支付配置
alipay:
  # 应用Id
  appId: 2021000121694962
  # 支付宝私钥公钥
  privateKey: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCJCfBLyW5pAeM51/iur5TyT/pXBNitchsNeP7fFOFiL0oaluWdnGZyl4rnNfwVKhzzwIXbOoemY6GD+RjEGywIhGqeNE72tiausoYLebU4eb1tXI6HXQYt2odw0k93HfVagnehsr5Y2CzLxU+OgRozAZeWFUdDcOJiAgJtEkr6/l8a54bUITmBszgz2xG0goFbEUT5BUGyr9tHXmMiT7GVS1QWoeSMthGgxKmlZAI4a0UXDwffZcRj0K+ygTUL2dTNzuOrum9nPZLK7474ec4aLOPi1NND9ES1Ac/DtH6EkonbMHLdap4QHa1IOeDrNUqw3zJmwKsFzRsmcjhauGCjAgMBAAECggEBAIXBhKCEUFb/96g6y8i9KhVEyOTsnwzUBeGliqd0+vPZkmvXgvDOehQ5I+O/Bngl7bJg5IXxX/ug3UIx/OFUYCtEC8i056nYanMzXrCOr7oa4TCAGcG3o1NYK8CMFfH+9L7N/zR9gVq4TSjrQlamXksQr8NWq4MBCIV+zp1lMHhAJ7xoGmLeb49E08p3sYzCuQsjqjIzOxztnqGPwLi1hxZJRP7E+JGR2IjmEFtYj3h6NXdKmoJy6nC7jYYOuNlExazW/lRf00pHvN0L2CU/TN/YkcGDl0I8yTgy8RdvoAp2vmrnpgN+ngEL4/0JVt8fFJ7KcfzPq9rW9skJDgt7uekCgYEAxPt4sgduHaG3YeuA1zZfc6bwvJUA/wL4xZ9JRKy6UT0mnT5oPOkVgEo6ryoP+P/2DjpkbewA9guafSYD5x9qWsAnNkBXK21UMZjI3ETncS6E6MIHJ4kUsG29G3tadTwqqUeMaFfpFwSUW3vXTxvEAJyxcHFTqu/UZBZlmYDTvwcCgYEAshjOYJmMy6ByB51pDlomN0gXsN01nNkmTLln6JXvaFdXcXoJaqdPu88YQTl+oXZ/x6y1m5t+p+La7/fP08rqaphMv/asye3KDhDfBTQg0/QM/JSfKetzQe2QwyUQCUQ3aq9yZVTuLnoLugQzVF9v3ZyFUdcA4svzOctKXTDuToUCgYEAxGoLm1kVT66k8JqnSfEJlIRtn1zkNWN9M3D02elxjvfuvPQxdCrmKZnakjba3mo7q0xGP+UHwE8pqIhzc847emoHr2zQfpjxTtMN1bVPIehE1uJByAZD/vgtjG2fcS6hS1Hwi0q9PRpv5BjERDlnY0TbGUenKdcibPp4LGvst5kCgYBy8H+A6JhtcoclUvnSQWwYkXZ4tss7Bwooyh+9g8aW2IeevNwG8SQMWYOV1L1dB1VAUL6ERr5fK5GQ/aYrUfIoCVK/MTwitkyI92p3uUTWhdM7z89JBqPEEMY0q17GHDiHqeNycnWlmS6oRr253j4cEEAaqV/w/x9iVUkRC9tA4QKBgBv2TtVFxJJY+3nTx/L9AFImvZDgEzTH4RXWTTatK34skYZAitQbiuA6BPJ+4lfPvxsoDLa6tYmN/ZH2nBulhffzTUhOqLSM4tiYoKblf1gmmEWotk1p5sG8/6CcZEfPDkoLoSkOhTTznCE+pa4z95WFZq+reJAhV82GXC/YuV6l
  publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAg/Sk0xCJXCvdRILCK1CkBshdjN/vg0m+wEhGlGnFX3kQJinaoLnTLz9iYQqRIu5YhoL5BKwkmtSd/CRpddKTWzLvocDGibPHFBNSCRpRv325iMFe9q2FYcWG14sh5JHmu3scaVqhOsQMvhhtcvOJU4kRNuHYWUXU6vB6SwlQQvV5NlNOGSl8FXnm4o/5b9Rk9hl7dw9RKFcoqcitQ/THkL2SSJpsnYpy6OKfN0GeimchAqukfJL6kXh9Goly0PM4q/fHV2YWmgf/3mRLB8JHBUUXRcswlJtPsRaARCN35MwnNyGqYfLHwtRLYirSmuLJg/pFfxXHA34X2ySy94iZVwIDAQAB
  # 支付完成后同步跳转的路径
  #  returnUrl: http://IP:端口/success.html
  returnUrl: http://www.baidu.com
  # 支付完成后异步调用的地址，返回结果中，确认收款成功的key值是 trade_status
  notifyUrl: http://47.100.220.20:10001/notify
  # 签名方式
  signType: RSA2
  # 编码格式
  charset: utf-8
  # 支付宝网关
  gatewayUrl: https://openapi.alipaydev.com/gateway.do

spring:
  rabbitmq:
    host: 124.71.161.198
    port: 5673 #jingranshi5673
    username: admin
    password: admin
    virtual-host: shiyi